export const LOGIN_CONSTANTS = {
    PASSWORD_MIN: 2,
    PASSWORD_MAX: 80,
    USERNAME_MIN: 2,
    USERNAME_MAX: 20
};

export const USER_CONSTANTS = {
    PASSWORD_MIN: LOGIN_CONSTANTS.PASSWORD_MIN,
    PASSWORD_MAX: LOGIN_CONSTANTS.PASSWORD_MAX,
    USERNAME_MIN: LOGIN_CONSTANTS.USERNAME_MIN,
    USERNAME_MAX: LOGIN_CONSTANTS.USERNAME_MAX,
    FULL_NAME_MIN: 2,
    FULL_NAME_MAX: 500
};

export const REGISTER_CONSTANTS = {
};
